export enum InfraConfigEnum {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  GITHUB_SCOPE = 'GITHUB_SCOPE',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',
  MICROSOFT_CALLBACK_URL = 'MICROSOFT_CALLBACK_URL',
  MICROSOFT_SCOPE = 'MICROSOFT_SCOPE',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',
}

export enum InfraConfigEnumForClient {
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  GITHUB_SCOPE = 'GITHUB_SCOPE',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',
  MICROSOFT_CALLBACK_URL = 'MICROSOFT_CALLBACK_URL',
  MICROSOFT_SCOPE = 'MICROSOFT_SCOPE',
}
